version = 1
SPDX-PackageName = "vector_vendor"
SPDX-PackageSupplier = "David Bensoussan <d.bensoussan@proton.me>"
SPDX-PackageDownloadLocation = "https://github.com/Minipada/vector_vendor"

[[annotations]]
path = ["**.md", "LICENSE.md", ".gitignore"]
SPDX-FileCopyrightText = "2022-2026 David Bensoussan"
SPDX-License-Identifier = "MPL-2.0"
